#!/bin/bash

dir="$(dirname "${BASH_SOURCE[0]}")"
linter_dir="${dir}/linters"

rc=0
for linter in "${linter_dir}"/*; do
    linter_name="$(basename "${linter}")"
    echo "=== ${linter_name} ==="
    "${linter}" || rc=1
done
exit "${rc}"
