name: Quality Tests
on:
    - push

jobs:
    rubocop:
        name: Rubocop
        runs-on: ubuntu-20.04
        container: ruby:2.7
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Bundle
              run: bundle install
            - name: Rubocop
              run: bundle exec rubocop -D
    lint:
        name: Lint
        runs-on: ubuntu-20.04
        container: ruby:2.7
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Bundle
              run: bundle install
            - name: Lint
              run: ./.support/lint
